---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-exp
parameters:
  fsType: ext4
  type: gp3
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  storageClassName: "gp3-exp"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
