# Shown below are two ways of extracting secrets from the Secret Manager
# The secrets must already exist in Secret Manager


---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: 12-example
spec:
  provider: aws
  parameters:
    region: eu-central-2
    objects: |
      - objectName: staging/myapp-secret-v2
        objectType: secretsmanager
        jmesPath:
            - path: username
              objectAlias: myusername
            - path: password
              objectAlias: mypassword
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: myusername
          key: k8s-myusername
        - objectName: mypassword
          key: k8s-mypassword
