---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: 12-example
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::058264202072:role/production-virtual_os-myapp-secrets
