---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-linux
parameters:
  fsType: ext4
  type: gp3
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linux-pvc
  namespace: linux-os
spec:
  storageClassName: "gp3-linux"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi