---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
  namespace: stateful-app
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      containers:
        - name: myapp
          image: aputra/myapp-195:v2
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
