---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app-1
  namespace: efs
spec:
  containers:
    - name: efs-app-1
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) from efs-app-1>> /data/out1.txt; sleep 5; done",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-pvc

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app-2
  namespace: efs
spec:
  containers:
    - name: efs-app-2
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) from efs-app-2 >> /data/out1.txt; sleep 5; done",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-pvc
