---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: windows-production
spec:
  acme:
    email: n.hamad@hotmail.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: windows-production-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx
